function [E,J] = joint1_IK(in1,in2)
%JOINT1_IK
%    [E,J] = JOINT1_IK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Aug-2019 16:45:03

q1 = in2(1,:);
q2 = in2(2,:);
x1 = in1(1,:);
y1 = in1(2,:);
z1 = in1(3,:);
t2 = cos(q2);
t3 = sin(q1);
t4 = t2.*t3.*(3.3e1./1.0e2);
t5 = cos(q1);
t6 = sin(q2);
t7 = t2.*t5.*(3.3e1./1.0e2);
E = [t7-x1;t4-y1;t6.*(-3.3e1./1.0e2)-z1];
if nargout > 1
    J = reshape([-t4,t7,0.0,t5.*t6.*(-3.3e1./1.0e2),t3.*t6.*(-3.3e1./1.0e2),t2.*(-3.3e1./1.0e2)],[3,2]);
end
