function dx = trig_dyn_toPeak(tdummy,in2,udummy)
%TRIG_DYN_TOPEAK
%    DX = TRIG_DYN_TOPEAK(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    17-Oct-2019 16:06:35

cq = in2(1,:);
q_dot_0 = in2(4,:);
q_ddot = in2(3,:);
sq = in2(2,:);
t = in2(5,:);
t2 = q_ddot.*t;
t3 = q_dot_0+t2;
dx = [-sq.*t3;cq.*t3;0.0;0.0;1.0];
