function dz = arm_dyn_toPeak(tdummy,in2,udummy)
%ARM_DYN_TOPEAK
%    DZ = ARM_DYN_TOPEAK(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jul-2019 16:22:36

t = in2(5,:);
theta_dot_0 = in2(3,:);
theta_dot_pk = in2(4,:);
x = in2(1,:);
y = in2(2,:);
t2 = theta_dot_0.*2.0;
t3 = t2-theta_dot_pk.*2.0;
t4 = theta_dot_0-t.*t3;
dz = [-t4.*y;t4.*x;0.0;0.0;1.0];
