function dz = arm_dyn_toStop(tdummy,in2,udummy)
%ARM_DYN_TOSTOP
%    DZ = ARM_DYN_TOSTOP(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jul-2019 16:22:36

t = in2(5,:);
theta_dot_pk = in2(4,:);
x = in2(1,:);
y = in2(2,:);
t2 = t-1.0./2.0;
t3 = theta_dot_pk-t2.*theta_dot_pk.*2.0;
dz = [-t3.*y;t3.*x;0.0;0.0;1.0];
