function dz = arm_dyn_toPeak_ODE(t,in2)
%ARM_DYN_TOPEAK_ODE
%    DZ = ARM_DYN_TOPEAK_ODE(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Jul-2019 18:05:00

t = in2(4,:);
theta_dot_0 = in2(2,:);
theta_dot_pk = in2(3,:);
dz = [theta_dot_0-t.*(theta_dot_0.*2.0-theta_dot_pk.*2.0);0.0;0.0];
