function dz = arm_dyn_toStop_ODE(t,in2)
%ARM_DYN_TOSTOP_ODE
%    DZ = ARM_DYN_TOSTOP_ODE(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    30-Jul-2019 18:05:01

t = in2(4,:);
theta_dot_pk = in2(3,:);
dz = [theta_dot_pk-theta_dot_pk.*(t-1.0./2.0).*2.0;0.0;0.0];
