function out1 = cos_traj_1_d_k_LagrangeRemainder(k,p0,t,v0)
%cos_traj_1_d_k_LagrangeRemainder
%    OUT1 = cos_traj_1_d_k_LagrangeRemainder(K,P0,T,V0)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Nov-2021 20:04:43

out1 = t.^4.*cos(p0+t.*v0+(k.*t.^2)./2.0).*(-1.0./8.0);
