function out1 = cos_traj_1_d_k_LagrangeRemainder(k,p0,t,v0)
%COS_TRAJ_1_D_K_LAGRANGEREMAINDER
%    OUT1 = COS_TRAJ_1_D_K_LAGRANGEREMAINDER(K,P0,T,V0)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Nov-2021 22:41:49

out1 = t.^12.*cos(p0+t.*v0+(k.*t.^2)./2.0).*(-2.170138888888889e-5);
