function out1 = sin_traj_1_d_k_LagrangeRemainder(k,p0,t,v0)
%sin_traj_1_d_k_LagrangeRemainder
%    OUT1 = sin_traj_1_d_k_LagrangeRemainder(K,P0,T,V0)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Nov-2021 22:29:24

out1 = t.^12.*sin(p0+t.*v0+(k.*t.^2)./2.0).*(-2.170138888888889e-5);
