function sin_traj_1_poly = sin_traj_1_TaylorExpansion(k,p0,tmid,v0)
%SIN_TRAJ_1_TAYLOREXPANSION
%    SIN_TRAJ_1_POLY = SIN_TRAJ_1_TAYLOREXPANSION(K,P0,TMID,V0)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Nov-2021 22:41:50

t2 = tmid.*v0;
t3 = p0+t2;
t4 = cos(t3);
t5 = sin(t3);
sin_traj_1_poly = t5+(k.*t4.*tmid.^2)./2.0-(k.^2.*t5.*tmid.^4)./8.0-(k.^3.*t4.*tmid.^6)./4.8e+1+(k.^4.*t5.*tmid.^8)./3.84e+2+(k.^5.*t4.*tmid.^10)./3.84e+3;
