function out1 = sin_traj_2_d_t_LagrangeRemainder(k,p0,t,v0)
%sin_traj_2_d_t_LagrangeRemainder
%    OUT1 = sin_traj_2_d_t_LagrangeRemainder(K,P0,T,V0)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Nov-2021 20:04:44

t2 = t.^2;
t3 = v0.*2.0;
t5 = t.*v0.*-2.0;
t7 = v0./4.0;
t4 = t.*t3;
t6 = t2.*v0;
t8 = -t7;
t10 = t3+t5;
t9 = -t6;
t11 = p0+t4+t8+t9;
t12 = cos(t11);
out1 = t10.*t12-(k.*t12.*(t-1.0))./2.0+(k.*t10.*sin(t11).*(-t+t2./2.0+1.0./4.0))./2.0;
