function dz1 = arm_vol_dyn_abs_l1(tdummy,in2,udummy)
%ARM_VOL_DYN_ABS_L1
%    DZ1 = ARM_VOL_DYN_ABS_L1(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Jun-2019 17:52:31

c1 = in2(3,:);
s1 = in2(4,:);
dz1 = [c1;s1;0.0;0.0;0.0;0.0;0.0];
