function dz2 = arm_vol_dyn_abs_l2(tdummy,in2,udummy)
%ARM_VOL_DYN_ABS_L2
%    DZ2 = ARM_VOL_DYN_ABS_L2(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    16-Jun-2019 17:52:31

c2 = in2(5,:);
s2 = in2(6,:);
dz2 = [c2;s2;0.0;0.0;0.0;0.0;0.0];
