function dw = arm_dyn_toPeak_3D_ODE(t,in2)
%ARM_DYN_TOPEAK_3D_ODE
%    DW = ARM_DYN_TOPEAK_3D_ODE(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Aug-2019 16:11:05

phi_dot_0 = in2(4,:);
phi_dot_pk = in2(6,:);
theta_dot_0 = in2(5,:);
theta_dot_pk = in2(7,:);
x = in2(1,:);
y = in2(2,:);
z = in2(3,:);
t2 = phi_dot_0.*2.0;
t3 = phi_dot_pk.*2.0;
t4 = t2-t3;
t5 = phi_dot_0-t.*t4;
t6 = x.^2;
t7 = y.^2;
t8 = t6+t7;
t9 = 1.0./sqrt(t8);
t10 = theta_dot_0.*2.0;
t13 = theta_dot_pk.*2.0;
t11 = t10-t13;
t14 = t.*t11;
t12 = -t14+theta_dot_0;
dw = [-t5.*y-t9.*t12.*x.*z;t5.*x-t9.*t12.*y.*z;sqrt(t8).*t12;0.0;0.0;0.0;0.0];
