function dw = arm_dyn_toStop_3D_ODE(t,in2)
%ARM_DYN_TOSTOP_3D_ODE
%    DW = ARM_DYN_TOSTOP_3D_ODE(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Aug-2019 16:11:05

phi_dot_pk = in2(6,:);
theta_dot_pk = in2(7,:);
x = in2(1,:);
y = in2(2,:);
z = in2(3,:);
t2 = t-1.0./2.0;
t3 = phi_dot_pk-phi_dot_pk.*t2.*2.0;
t4 = x.^2;
t5 = y.^2;
t6 = t4+t5;
t7 = 1.0./sqrt(t6);
t9 = t2.*theta_dot_pk.*2.0;
t8 = -t9+theta_dot_pk;
dw = [-t3.*y-t7.*t8.*x.*z;t3.*x-t7.*t8.*y.*z;sqrt(t6).*t8;0.0;0.0;0.0;0.0];
