function dw = arm_dyn_toPeak_3D(tdummy,in2,udummy)
%ARM_DYN_TOPEAK_3D
%    DW = ARM_DYN_TOPEAK_3D(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Aug-2019 16:11:04

cph = in2(5,:);
phi_dot_0 = in2(6,:);
phi_dot_pk = in2(8,:);
sph = in2(4,:);
t = in2(10,:);
theta_dot_0 = in2(7,:);
theta_dot_pk = in2(9,:);
x = in2(1,:);
y = in2(2,:);
z = in2(3,:);
t2 = phi_dot_0.*2.0;
t3 = phi_dot_pk.*2.0;
t4 = t2-t3;
t11 = t.*t4;
t5 = phi_dot_0-t11;
t6 = theta_dot_0.*2.0;
t9 = theta_dot_pk.*2.0;
t7 = t6-t9;
t10 = t.*t7;
t8 = -t10+theta_dot_0;
dw = [-t5.*y-cph.*t8.*z;t5.*x-sph.*t8.*z;t8.*(cph.*x+sph.*y);cph.*t5;-sph.*t5;0.0;0.0;0.0;0.0;1.0];
